"""create assessment schema

Revision ID: 431544896b81
Revises: 
Create Date: 2025-11-20 18:48:18.497406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431544896b81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('azienda_nome', sa.Text(), nullable=False),
    sa.Column('settore', sa.Text(), nullable=True),
    sa.Column('dimensione', sa.Text(), nullable=True),
    sa.Column('referente', sa.Text(), nullable=True),
    sa.Column('effettuato_da', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('risposte_json', sa.Text(), nullable=True),
    sa.Column('punteggi_json', sa.Text(), nullable=True),
    sa.Column('raccomandazioni', sa.Text(), nullable=True),
    sa.Column('pareto_recommendations', sa.Text(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=False),
    sa.Column('data_chiusura', sa.DateTime(), nullable=True),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assessment_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('process', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_not_applicable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_result')
    op.drop_table('local_users')
    op.drop_table('assessment_session')
    # ### end Alembic commands ###
